#!/bin/bash

# Stop nginx service
service nginx stop

# Replace the nginx configuration to run as nginx user and listen on port 8080
sed -i 's/user\s*nginx;/user nginx;\n    listen 8080;/g' /etc/nginx/nginx.conf

# Start nginx service
service nginx start
